import type { EventItem, Photo } from "@/lib/types";

/**
 * A picture for an event that came with none.
 *
 * Imported events arrive without a photograph and we do not take other
 * people's, so the card, the social preview and the structured-data image all
 * had nothing. These covers are labelled graphics in the site's own palette —
 * deliberately not photographs, so nobody reads them as a picture of the
 * event itself.
 *
 * Generated by scripts/build-event-covers.mjs.
 */

const CATEGORIES = new Set([
  "concert", "theatre", "dance", "festival", "exhibition", "screening",
  "talk", "workshop", "sport", "market", "family", "other",
]);

const LABEL: Record<string, { el: string; en: string }> = {
  concert: { el: "Συναυλία", en: "Concert" },
  theatre: { el: "Θέατρο", en: "Theatre" },
  dance: { el: "Χορός", en: "Dance" },
  festival: { el: "Φεστιβάλ", en: "Festival" },
  exhibition: { el: "Έκθεση", en: "Exhibition" },
  screening: { el: "Προβολή", en: "Screening" },
  talk: { el: "Ομιλία", en: "Talk" },
  workshop: { el: "Εργαστήρι", en: "Workshop" },
  sport: { el: "Αθλητικά", en: "Sport" },
  market: { el: "Αγορά", en: "Market" },
  family: { el: "Για οικογένειες", en: "For families" },
  other: { el: "Εκδήλωση", en: "Event" },
};

/**
 * The event's own photograph when it has one, otherwise its category cover.
 *
 * The alt text says what the image is — a category card — rather than
 * describing a scene that was never photographed.
 */
export function eventCover(event: Pick<EventItem, "photos" | "type">): Photo {
  const own = event.photos?.[0];
  if (own) return own;

  const key = CATEGORIES.has(event.type) ? event.type : "other";
  const label = LABEL[key];
  return {
    url: `/photos/event-${key}.webp`,
    alt: {
      el: `${label.el} στη Θεσσαλονίκη — εικόνα κατηγορίας του ThessalonikiHub`,
      en: `${label.en} in Thessaloniki — a ThessalonikiHub category card`,
    },
  };
}
